# Generated by Django 4.1.2 on 2023-06-17 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_alter_oauthprofile_table_address'),
        ('goods', '0007_sku_stock_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('order_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='訂單編號')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='訂單總金額')),
                ('total_count', models.IntegerField(verbose_name='商品總數')),
                ('pay_method', models.SmallIntegerField(default=1, verbose_name='支付方式')),
                ('freight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='運費')),
                ('status', models.SmallIntegerField(choices=[(0, '已取消'), (1, '待付款'), (2, '待發貨'), (3, '待收貨'), (4, '訂單完成')], verbose_name='訂單狀態')),
                ('receiver', models.CharField(max_length=10, verbose_name='收件人')),
                ('receiver_phone', models.CharField(max_length=10, verbose_name='收件人手機')),
                ('address', models.CharField(max_length=100, verbose_name='收件地址')),
                ('remark', models.TextField(verbose_name='商品備註')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
            options={
                'db_table': 'orders_order_info',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='數量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='單價')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('order_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderinfo')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.sku')),
            ],
            options={
                'db_table': 'orders_order_goods',
            },
        ),
    ]
