# Generated by Django 4.1.2 on 2023-07-04 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderinfo',
            options={'verbose_name': '訂單訊息', 'verbose_name_plural': '訂單訊息'},
        ),
    ]
