# Generated by Django 4.1.2 on 2023-05-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='default_image_uel',
            field=models.ImageField(default=None, upload_to='sku', verbose_name='默認圖片'),
        ),
    ]
