# Generated by Django 4.1.2 on 2023-05-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_sku_default_image_uel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spusaleattr',
            name='name',
            field=models.CharField(max_length=50, verbose_name='SPU屬性名稱'),
        ),
    ]
