# Generated by Django 4.1.2 on 2023-05-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_spusaleattr_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spu',
            name='nutrition_facts',
            field=models.TextField(verbose_name='營養成份'),
        ),
    ]
