# Generated by Django 4.1.2 on 2023-05-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_spu_nutrition_facts'),
    ]

    operations = [
        migrations.AddField(
            model_name='spu',
            name='storage_method',
            field=models.CharField(default='', max_length=100, verbose_name='保存方式'),
        ),
    ]
