# Generated by Django 4.1.2 on 2023-05-25 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_spu_storage_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sku',
            old_name='default_image_uel',
            new_name='default_image_url',
        ),
    ]
