# Generated by Django 4.1.2 on 2023-05-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_rename_default_image_uel_sku_default_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='stock_number',
            field=models.IntegerField(default=0, verbose_name='庫存數量'),
        ),
    ]
