# Generated by Django 4.1.2 on 2023-07-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LangLangSpiderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='寵物名稱')),
                ('gender', models.CharField(max_length=10, verbose_name='寵物性別')),
                ('age', models.CharField(max_length=20, null=True, verbose_name='寵物年齡')),
                ('ligation', models.BooleanField(verbose_name='是否結紮')),
                ('be_helped', models.CharField(max_length=10, verbose_name='助養人數')),
                ('image', models.ImageField(default=None, max_length=2048, upload_to='langlang', verbose_name='浪浪圖片')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '浪浪資訊',
                'verbose_name_plural': '浪浪資訊',
                'db_table': 'langlang_info',
            },
        ),
    ]
