# Generated by Django 4.1.2 on 2023-07-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='langlangspiderinfo',
            name='deworming',
            field=models.CharField(max_length=20, null=True, verbose_name='體內外寄生蟲'),
        ),
        migrations.AddField(
            model_name='langlangspiderinfo',
            name='introduction',
            field=models.TextField(null=True, verbose_name='浪浪介紹'),
        ),
        migrations.AddField(
            model_name='langlangspiderinfo',
            name='personality',
            field=models.CharField(max_length=100, null=True, verbose_name='個性簡介'),
        ),
        migrations.AddField(
            model_name='langlangspiderinfo',
            name='vaccination',
            field=models.CharField(max_length=20, null=True, verbose_name='預防針'),
        ),
    ]
