# Generated by Django 4.1.2 on 2023-07-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0002_langlangspiderinfo_deworming_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='langlangspiderinfo',
            name='src',
            field=models.CharField(max_length=200, null=True, verbose_name='狗狗連結'),
        ),
    ]
