# Generated by Django 4.1.2 on 2023-05-10 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_birthday_alter_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthprofile',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
